version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: "devops"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - two-tier
    healthcheck:
      # Use mysqladmin to check if the database is ready
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost","-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  flask:
    build:
      context: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: "devops"
    networks:
      - two-tier
    restart: always
    depends_on:
      mysql:
        condition: service_healthy # Wait for MySQL to be fully ready before starting Flask
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  two-tier:

volumes:
  mysql_data:
